;; generated by Gemini
;; --- 1. 必須パッケージのセットアップ ---
(use-package vertico
  :ensure t
  :init
  (vertico-mode)
  :config
  ;; anything の操作感に合わせるキーバインド設定
  (define-key vertico-map (kbd "C-n") 'vertico-next)
  (define-key vertico-map (kbd "C-p") 'vertico-previous)
  (define-key vertico-map (kbd "C-M-v") 'vertico-next-group) ;; ページ送りに近い挙動
  (define-key vertico-map (kbd "C-M-y") 'vertico-previous-group)
  
  ;; 候補表示の遅延設定 (anything-input-idle-delay 0.2 に相当)
  ;; Verticoは標準で高速ですが、入力直後のチラつきを抑えたい場合はこちら
  (setq vertico-cycle t))

;; --- 2. 検索ロジック (Orderless) ---
(use-package orderless
  :ensure t
  :custom
  (completion-styles '(orderless basic))
  (completion-category-overrides '((file (styles basic partial-completion)))))

;; --- 3. 候補の注釈表示 (Marginalia) ---
(use-package marginalia
  :ensure t
  :init
  (marginalia-mode))

;; --- 4. anything の主要機能の代替 (Consult) ---
(use-package consult
  :ensure t
  :bind (
         ;; --- anything (C-x ;) の代わり ---
         ;; バッファ、最近のファイル、ブックマークを統合表示
         ("C-x ;" . consult-buffer)
         
         ;; --- anything-resume (C-x :) の代わり ---
         ;; 最後に実行した consult コマンドを再開
         ("C-x :" . vertico-repeat)

         ;; その他 anything でよく使われる機能の割り当て
         ("M-y"   . consult-yank-pop)      ;; anything-show-kill-ring
         ("M-s l" . consult-line)          ;; anything-occur
         ("M-s r" . consult-ripgrep)       ;; anything-do-grep (要 ripgrep)
         ("M-g i" . consult-imenu)         ;; anything-imenu
         )
  :hook (completion-list-mode . consult-preview-at-point-mode)
  :init
  ;; C-x : (vertico-repeat) を使うために履歴を保存する設定
  (use-package savehist
    :init
    (savehist-mode)))

;; --- 5. 履歴保存の有効化 ---
(use-package vertico-repeat
  :after vertico
  :ensure nil ;; vertico パッケージに含まれています
  :hook (minibuffer-setup . vertico-repeat-save))
